In [11]:
!ls ../

LICENSE   README.md  data    docker-compose.yaml  notebooks    pyproject.toml
Makefile  cybulde    docker  logs.log		  poetry.lock  setup.cfg

In [17]:
!ls ../data/raw/ghc

AnnotatorIAT_and_Attitudes.csv	ghc_test.tsv
GabHateCorpus_annotations.tsv	ghc_train.tsv

In [16]:
!pwd

/usr/bin/sh: 1: cwd: not found

In [19]:
import pandas as pd

In [24]:
train_df = pd.read_csv("../data/raw/ghc/ghc_train.tsv", sep="\t", header = 0)
test_df = pd.read_csv("../data/raw/ghc/ghc_test.tsv", sep="\t", header = 0)

In [28]:
print(f"{train_df.shape = }")
print(f"{test_df.shape = }")

train_df.shape = (22036, 4)
test_df.shape = (5510, 4)

In [ ]:
"""
HD - Violating Human Dignity
CV - Calls for violoce
VO - Vulgarity or offensive language directed at another

Will combine all of these 3 into 1 label 
and say that if any of these occur then 
cyber bullying has occured
"""

In [29]:
train_df.head(10)

                                                text  hd  cv  vo
0  He most likely converted to islam due to his n...   0   0   0
1  So Ford lied about being a psychologist. Recor...   0   0   0
2     Jobs. Education. Ending abuse of Nation. CA43.   0   0   0
3  I share a lot of your values, & like many who ...   0   0   0
4  I am so ready to get back to blogging! www.ben...   0   0   0
5  taking a look at new opportunity called FX Pro...   0   0   0
6  Reflecting back when I was in school with Spec...   0   0   0
7  Let's be honest everyone, last year there were...   0   0   0
8                          2007 Nuke plant in Syria    0   0   0
9  NBC's Chuck Todd Thinks He's Figured It All Ou...   0   0   0

In [30]:
test_df.head(10)

                                                text  hd  cv  vo
0  https://www.youtube.com/watch?v=kACWpKAKtak A ...   0   0   0
1  Very nice! I tend to get tired of the constant...   0   0   0
2        Watch today. https://circumcisionmovie.com/   0   0   0
3  " Thinking Venues " First Color Layer blocking...   0   0   0
4  What about death penalty for perpetrators  and...   0   0   0
5                   You have insecurities? Fuck you    0   0   0
6  Powerful Truths About Donald Trump the Media D...   0   0   0
7         Just saw an Oreo cookie commercial. Drool.   0   0   0
8   I bet a neural net with half a dozen nodes co...   0   0   0
9  Country by country, the 'Prague Spring' that w...   0   0   0

In [31]:
!ls ../data/raw

ghc  jigsaw-toxic-comments  twitter

In [32]:
import dask as dd